Rework create-netboot [issue376]; small update of grml-terminalserver-config

diff --git a/create-netboot b/create-netboot
--- a/create-netboot
+++ b/create-netboot
@@ -7,11 +7,19 @@ isExistent $SHARED_PROG_VARS_ die
 
 function actionPkg
 { 
-    local tmp_=`mktemp -td terminalserver_grub.XXXXXX` || die "could not create tmpfile"
-    local version_="`cat /etc/grml_version`"
-    version_=${version_%% *}
+    local pwd_="$(pwd)"
+    local tmp_="$(mktemp -td terminalserver_grub.XXXXXX)" || die "could not create tmpfile"
+
+    # version information:
+    local version_="$(cat /etc/grml_version)"
+    local version_number_="$(awk '{print $2}' /etc/grml_version)"
+    case $version_number_ in
+         [0-9]*) version_="${version_%% *}"_${version_number_} ;;
+         *)      version_="${version_%% *}" ;;
+    esac
+    
     local path_="$tmp_/grml_netboot_package_$version_"
-    mkdir $path_
+    mkdir "$path_"
 
     cp $NETBOOT_PACKAGE_CONF_FILE_ $CONFIG_
     echo "executing grml-terminalserver-config initrd"
@@ -26,11 +34,10 @@ function actionPkg
     grml-terminalserver-config grubConf $path_/grub_enabled_nics
     cp $PATH_/grub.img $path_
 
-    pushd $tmp_
-    tar cjf grml_netboot_package_${version_}.tar.bz2 $path_
-    popd
-    mv -b $tmp_/grml_netboot_package_${version_}.tar.bz2 .
-    rm -rf $tmp_
+    ( cd "$tmp_" && tar jcf "$pwd_"/grml_netboot_package_${version_}.tar.bz2 "grml_netboot_package_$version_" )
+
+    rm -rf "$tmp_"
+    echo "grml_netboot_package_${version_}.tar.bz2 has been created."
 }
 
 checkRoot die "You have to be root to use this program"
