Disable grub feature by default

diff --git a/create-netboot b/create-netboot
--- a/create-netboot
+++ b/create-netboot
@@ -8,7 +8,7 @@ isExistent $SHARED_PROG_VARS_ die
 function actionPkg
 { 
     local pwd_="$(pwd)"
-    local tmp_="$(mktemp -td terminalserver_grub.XXXXXX)" || die "could not create tmpfile"
+    local tmp_="$(mktemp -td terminalserver.XXXXXX)" || die "could not create tmpfile"
 
     # version information:
     local version_="$(cat /etc/grml_version)"
@@ -28,11 +28,6 @@ function actionPkg
     # tftpd config
     grml-terminalserver config tftp
     cp -r $TFTPD_DATA_DIR_ $path_
-
-    # grub
-    awk '/ on$/{print $1}' $GRUB_NIC_CONF_ >$path_/grub_enabled_nics
-    grml-terminalserver-config grubConf $path_/grub_enabled_nics
-    cp $PATH_/grub.img $path_
 
     ( cd "$tmp_" && tar jcf "$pwd_"/grml_netboot_package_${version_}.tar.bz2 "grml_netboot_package_$version_" )
 
